INCLUDE( ${CMAKE_MODULE_PATH}/configure.cmake )
INCLUDE( ${CMAKE_MODULE_PATH}/configure-project-main.cmake )
INCLUDE( ${CMAKE_MODULE_PATH}/configure-project-test.cmake )
INCLUDE( ${CMAKE_MODULE_PATH}/configure-compiler-gcc.cmake )
INCLUDE( ${CMAKE_MODULE_PATH}/configure-jni.cmake )
INCLUDE( ${CMAKE_MODULE_PATH}/configure-alternative-dependencies.cmake )
INCLUDE( ${CMAKE_MODULE_PATH}/configure-cppunit.cmake )

INCLUDE( ${CMAKE_MODULE_PATH}/project-main.cmake )
INCLUDE( ${CMAKE_MODULE_PATH}/project-test.cmake )
INCLUDE( ${CMAKE_MODULE_PATH}/project-alternative.cmake )
